### ISSUE TITLE
Addition of ReadMe

### ISSUE THREAD

**Issue by Sarthak2601** [technojam/TechnoJam-App#2]
The ReadMe file should contain relevant information about the application's features and the techniques used to build those features. Please refer [this](https://docs.google.com/document/d/109dGQjQZ_FahXmiVC3NvTepGu8oCSJUSpYg9KaCN9z0/edit?usp=sharing) doc before proceeding.

**Comment by scottmacdonnell** [comment]
Hi there, I can make one for you just give me a few minutes and I will make a pull request.
